version: '3.9'
services:
  backend:
    build:
      context: ./backend
    container_name: nutrition-backend
    environment:
      - DATABASE_URL=sqlite:////data/nutrition.db
      - DEV_AUTO_CREATE=0
      - FLASK_ENV=production
    volumes:
      - backend_data:/data
    ports:
      - "5000:5000"  # غير المنفذ الخارجي إلى 5000
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  backend_data:
