name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - feature/**

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nutrition_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Configure env
        run: |
          echo "DATABASE_URL=postgresql+psycopg2://postgres:postgres@localhost:5432/nutrition_test" >> $GITHUB_ENV
          echo "FLASK_ENV=testing" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret" >> $GITHUB_ENV
          echo "NUTRITION_API=usda" >> $GITHUB_ENV
          echo "NUTRITION_API_KEY=dummy" >> $GITHUB_ENV
      - name: Run migrations
        working-directory: backend
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          . ../venv/bin/activate
          flask db upgrade
      - name: Run pytest
        working-directory: backend
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          . ../venv/bin/activate
          python -m pytest -q

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install flake8
        run: |
          pip install flake8
      - name: Run flake8
        run: |
          flake8 backend || true
